### ISSUE TITLE
[cmake] verify Python installation

### ISSUE THREAD

**Issue by dev-zero** [cp2k/dbcsr#157]
`CMake` should check all requirements to give meaningful error messages instead of the build failing later. Currently it does not check for Python and/or Numpy:

```
Wrote kernel string to file
-> cusmm_kernels.h
Traceback (most recent call last):
  File "../../../../../src/acc/libsmm_acc/libcusmm/generate_parameters.py", line 18, in <module>
    from kernels.cusmm_predict import params_dict_to_kernel
  File "/users/tiziano/work/dbcsr/dbcsr/src/acc/libsmm_acc/libcusmm/kernels/cusmm_predict.py", line 11, in <module>
    import numpy as np
ImportError: No module named numpy
```

**Comment by dev-zero** [comment]
... furthermore, CMake should favor Python 3 over 2 if both are available but Python 2 is the default interpreter.
