### ISSUE TITLE
Build fails on macOS with fypp errors

### ISSUE THREAD

**Issue by barracuda156** [cp2k/dbcsr#644]
**Describe the bug**
Build fails with `fypp` errors.

```
Executing:  cd "/opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build" && ninja -j6 all -j6 -v 
[1/346] cd /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build/src && /opt/local/bin/python3.10 /opt/local/bin/fypp-3.10 --line-numbering --line-marker-format=gfortran5 /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/dbcsr-2.5.0/src/acc/dbcsr_acc_event.F /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build/src/acc/dbcsr_acc_event.F
FAILED: src/acc/dbcsr_acc_event.F /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build/src/acc/dbcsr_acc_event.F 
cd /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build/src && /opt/local/bin/python3.10 /opt/local/bin/fypp-3.10 --line-numbering --line-marker-format=gfortran5 /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/dbcsr-2.5.0/src/acc/dbcsr_acc_event.F /opt/local/var/macports/build/_opt_PPCRosettaPorts_math_dbcsr/dbcsr/work/build/src/acc/dbcsr_acc_event.F
Traceback (most recent call last):
  File "/opt/local/bin/fypp-3.10", line 33, in <module>
    sys.exit(load_entry_point('fypp==3.1', 'console_scripts', 'fypp')())
  File "/opt/local/bin/fypp-3.10", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```
It also fails if Ninja is not used with CMake, likewise.

**Expected behavior**
It should build fine :)

**Environment:**
macOS 10.6.8
gcc 12.2.0
mpich-gcc12 @4.0.2+fortran
cmake-devel @20221130-3.25.1
ninja @1.11.1
OpenBLAS @0.3.21+gcc12+lapack+native
python310 @3.10.8
py-fypp @3.1

**Comment by barracuda156** [comment]
Please ignore, this was due to `py-fypp` built in a wrong way.
